### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by SyrianSpock** [SyrianSpock/tof-sensor-board#1]
Schematic & PCB done.
Anyone care for a review ?

**Comment by Stapelzeiger** [comment]
The input diode is the wrong way around.
Edit: same for the LEDs

**Comment by Stapelzeiger** [comment]
The VDDA capacitors are probably not needed since we won't use the ADC.

**Comment by Stapelzeiger** [comment]
Concerning the layout:
- We should add a 2nd footprint for the upward facing sensor.
- I suggest to use through hole footprints for the programming connector. We could split the connector if necessary and we could drop the VCC and GND since we can power it through the bus connector.
- Connect the M2 mount pads to GND and move them inwards by ~0.8-1mm

**Comment by froj** [comment]
> The input diode is the wrong way around.
> Edit: same for the LEDs

I was quite confused, because in the .pdf it's actually the right way around. But yeah, need to change the schematics.

Also, IMO the power LED would be more useful as a status/heartbeat LED.

**Comment by SyrianSpock** [comment]
> The input diode is the wrong way around.
> Edit: same for the LEDs

On the schematic, the symbols look good, except it seems for some reason they decided to flip the pins...
I'll correct the footprint.

> The VDDA capacitors are probably not needed since we won't use the ADC.

Removed.

> I suggest to use through hole footprints for the programming connector. We could split the connector if necessary and we could drop the VCC and GND since we can power it through the bus connector.

I think there should be a group discussion to define a standard programming connector to be used.

> Connect the M2 mount pads to GND and move them inwards by ~0.8-1mm

Seeedstudio is going to hate us for doing this.

> Also, IMO the power LED would be more useful as a status/heartbeat LED.

+1

> We should add a 2nd footprint for the upward facing sensor.

Will do

**Comment by Stapelzeiger** [comment]
> Seeedstudio is going to hate us for doing this.

We will have to add it to the board outline

> I think there should be a group discussion to define a standard programming connector to be used.

I propose the 2mm connector used on the motor board, with the RX/TX optional

**Comment by SyrianSpock** [comment]
> We will have to add it to the board outline

Already the case

> I propose the 2mm connector used on the motor board, with the RX/TX optional

With or without power ?

**Comment by Stapelzeiger** [comment]
> With or without power ?

With power

**Comment by Capifourbe** [comment]
> Connect the M2 mount pads to GND and move them inwards by ~0.8-1mm

Ce n'est pas nécessaire de déplacé les pads. La moitié du pad est suffisant pour la fixation.
Quel est le diamètre des trous et des pads?

La carte est très grande... tu as essayé de la mettre dans la main?

**Comment by SyrianSpock** [comment]
> Quel est le diamètre des trous et des pads?

2.2mm le trou et 4.4mm le pad

> La carte est très grande... tu as essayé de la mettre dans la main?
> Non, Patrick avait proposé de mettre les 2 Picoblade CAN et le MCU sur la même face et le capteur sur le bord, alors j'ai fais le plus petit qui tient compte de tout ça.

Faudrait en rediscuter mercredi.
